"""empty message

Revision ID: 0fec9cbb8b81
Revises: cd990d0ddba5
Create Date: 2024-05-09 14:12:25.551093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fec9cbb8b81'
down_revision = 'cd990d0ddba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.Column('nombre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nombre_id'], ['people.id_persona'], ),
    sa.ForeignKeyConstraint(['planeta_id'], ['planets.id_planeta'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    # ### end Alembic commands ###
